version: 2

builds:
  - binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/leaktk/{{ .ProjectName }}/pkg/version.Version={{ .Version }} -X github.com/leaktk/{{ .ProjectName }}/pkg/version.Commit={{ .FullCommit }}

archives:
  - formats: tar.xz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      
homebrew_casks:
  - repository:
      owner: leaktk
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/leaktk/leaktk
    description: A growing toolkit of utilities for leak detection, mitigation and prevention.
    license: MIT
    completions:
      bash: "completions/bash/leaktk"
      zsh: "completions/zsh/_leaktk"
      fish: "completions/fish/leaktk.fish"
    url:
      verified: github.com/leaktk/leaktk
      
dockers:
  - image_templates:
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Containerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title=leaktk
      - --label=org.opencontainers.image.description="The Leak ToolKit"
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Containerfile
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title=leaktk
      - --label=org.opencontainers.image.description="The Leak ToolKit"
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "quay.io/leaktk/{{ .ProjectName }}:{{ .Major }}"
    image_templates:
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "quay.io/leaktk/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "quay.io/leaktk/{{ .ProjectName }}:latest"
    image_templates:
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "quay.io/leaktk/{{ .ProjectName }}:{{ .Version }}-arm64"

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    artifacts: all
    output: true
    args:
      - sign-blob
      - '--oidc-provider=github-actions'
      - '--bundle=${signature}'
      - '${artifact}'
      - --yes
