version: 2

builds:
  - binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/leaktk/{{ .ProjectName }}/pkg/version.Version={{ .Version }} -X github.com/leaktk/{{ .ProjectName }}/pkg/version.Commit={{ .FullCommit }}

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"

archives:
  - formats: tar.xz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: completions/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      
homebrew_casks:
  - repository:
      owner: leaktk
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/leaktk/leaktk
    description: A growing toolkit of utilities for leak detection, mitigation and prevention.
    license: MIT
    completions:
      bash: "completions/bash/leaktk"
      zsh: "completions/zsh/_leaktk"
      fish: "completions/fish/leaktk.fish"
    url:
      verified: github.com/leaktk/leaktk

dockers_v2:
  - images:
      - "quay.io/leaktk/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - "{ .Major }}.{{ .Minor }}"
      - "latest"
    labels:
      "org.opencontainers.image.title": "leaktk"
      "org.opencontainers.image.description": "The Leak ToolKit"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "MIT"

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    artifacts: all
    output: true
    args:
      - sign-blob
      - '--oidc-provider=github-actions'
      - '--bundle=${signature}'
      - '${artifact}'
      - --yes
