name: Build, sign and upload release artifacts

env:
  GO_VERSION: '1.25'
  GO111MODULE: on

on:
  push:
    tags:
      - "v[0-1].[0-9]+.[0-9]+"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  tests:
    uses: ./.github/workflows/testing.yml

  goreleaser:
    name: Create release artifacts
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # pin@v7.0.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # pin@v4.4.0
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # pin@v4.1.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # pin@v4.2.0
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # pin@v4.0.0
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # pin@v7.2.3
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # PAT with access to write contents to leaktk/homebrew-tap
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
          # The base64 of the contents of your '.p12' key.
          MACOS_SIGN_P12: ${{ secrets.MACOS_SIGN_P12 }}
          # The password to open the '.p12' key.
          MACOS_SIGN_PASSWORD: ${{ secrets.MACOS_SIGN_PASSWORD }}
          # The base64 of the contents of your '.p8' key.
          MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}
          # The ID of the '.p8' key.
          MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
          # The issuer UUID.
          MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}
          
